
[window]
dimensions = { columns = 100, lines=30 }
position = { x = 6, y = 6 }
padding = { x = 6, y =6 }
decorations = "None"
opacity = 0.9
blur = false
startup_mode = "Windowed"
title = "term"
dynamic_title =true
decorations_theme_variant = "None"
resize_increments = false

[scrolling]
history =10000
multiplier = 1

[selection]
save_to_clipboard=true

[font]

[colors]
cursor ={ text = "CellBackground", cursor = "CellForeground" }
vi_mode_cursor ={ text = "CellBackground", cursor = "#ac4242" }

[keyboard]
bindings = 	[{key ="Return",	mods = "Alt", action= "SpawnNewInstance"}
		,{key ="Escape",	mods = "Alt", action ="ToggleViMode"}
	#	,{key =":", mods="Shift",mode="~Alt", action ="ToggleViMode"}
		,{key ="q",		mods = "Alt", action ="Quit"}
		,{key ="p",mode="Vi", action ="Paste"}
		,

]

[mouse]

[general]
live_config_reload = true
working_directory ="None"
#doc:https://alacritty.org/config-alacritty.html
import=[]

