#!/usr/bin/env bash
#@~/.config/uwsm/env

export PATH="$PATH:${HOME}/.scripts:${HOME}/.local/bin:${HOME}/.config/emacs/bin"
export PYTHONPATH="$PYTHONPATH:~/.scripts/pylibs"
export C_INCLUDE_PATH+=':~/.scripts/cutil'
export LC_ALL=en_IN.UTF-8
export LANG=en_IN.UTF-8
export MANWIDTH=80
export MANPAGER="nvim +Man!"
export PSQL_PAGER="nvim +Man!"
export TERM='alacritty'
export EDITOR="nvim"
export FCEDIT="nvim"
