
--gesture
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.gesture({
    fingers = 4,
    direction = "horizontal",
    action = "workspace",
})
-- gesture = 3, horizontal, scroll_move
hl.gesture({
    fingers = 4,
    direction = "vertical",
    action = "fullscreen",
})
hl.gesture({
    fingers = 3,
    direction = "vertical",
    action = "float",
})
-- gesture = 3, left, scale: 1.5, float

--scrolling keybind
hl.bind("SUPER + comma", hl.dsp.layout("move -col"))
hl.bind("SUPER + period", hl.dsp.layout("move +col"))
hl.bind("SUPER + SHIFT + comma", hl.dsp.layout("swapcol l"))
hl.bind("SUPER + SHIFT + period", hl.dsp.layout("swapcol r"))
hl.bind("SUPER + ALT + comma", hl.dsp.layout("consume prev"))
hl.bind("SUPER + ALT + period", hl.dsp.layout("consume next"))
hl.bind("SUPER + ALT + SHIFT + comma", hl.dsp.layout("expel prev"))
hl.bind("SUPER + ALT + SHIFT + period", hl.dsp.layout("expel next"))

--apps
hl.bind("SUPER + T", hl.dsp.exec_cmd("[float;size 900 700;center] alacritty"))
hl.bind("SUPER + R", hl.dsp.exec_cmd("rofi -show drun"))
hl.bind("SUPER + W", hl.dsp.exec_cmd("rofi -show windoscroll_mw"))
hl.bind("CTRL + SHIFT + T", hl.dsp.exec_cmd("alacritty"))
hl.bind("CTRL + SHIFT + W", hl.dsp.exec_cmd("~/.scripts/webapps.rofi.py launch"))
hl.bind("CTRL + SHIFT + E", hl.dsp.exec_cmd("alacritty -e bash -ic yazi"))
hl.bind("CTRL + SHIFT + G", hl.dsp.exec_cmd("[float;size 900 700;center] qutebrowser"))
hl.bind("CTRL + SHIFT + S", hl.dsp.exec_cmd("[float;size 600 400;move cursor_x-10 cursor_y-30] alacritty -e python -q -i ~/.scripts/pyshell.py"))
hl.bind("CTRL + SHIFT + A", hl.dsp.exec_cmd("[float;size 500 200;move cursor_x-10 cursor_y-30] alacritty -e qalc -c -e -i"))
hl.bind("CTRL + SHIFT + N", hl.dsp.exec_cmd("alacritty -e nvim"))
hl.bind("CTRL + SHIFT + B", hl.dsp.exec_cmd("emacsclient -c -a 'emacs'"))

-- Window Management
hl.bind("SUPER + Q", hl.dsp.window.close())
hl.bind("SUPER + M", hl.dsp.window.fullscreen({ mode = "maximized", action = "toggle" }))
hl.bind("SUPER + SHIFT + M", hl.dsp.window.fullscreen({ mode = "fullscreen", action = "toggle" }))
hl.bind("SUPER + F", hl.dsp.window.float({ action = "toggle" }))
hl.bind("SUPER + G", hl.dsp.group.toggle())

-- Numbered Workspaces
hl.bind("SUPER + 1", hl.dsp.focus({ workspace = 1 }))
hl.bind("SUPER + 2", hl.dsp.focus({ workspace = 2 }))
hl.bind("SUPER + 3", hl.dsp.focus({ workspace = 3 }))
hl.bind("SUPER + 4", hl.dsp.focus({ workspace = 4 }))
hl.bind("SUPER + 5", hl.dsp.focus({ workspace = 5 }))
hl.bind("SUPER + 6", hl.dsp.focus({ workspace = 6 }))
hl.bind("SUPER + 7", hl.dsp.focus({ workspace = 7 }))
hl.bind("SUPER + 8", hl.dsp.focus({ workspace = 8 }))
hl.bind("SUPER + 9", hl.dsp.focus({ workspace = 9 }))
hl.bind("SUPER + 0", hl.dsp.focus({ workspace = 10 }))
hl.bind("SUPER + BRACKETLEFT", hl.dsp.focus({ workspace = 11 }))
hl.bind("SUPER + U", hl.dsp.focus({ workspace = "e+1" }))
hl.bind("SUPER + I", hl.dsp.focus({ workspace = "e-1" }))

-- Move to Numbered Workspaces
hl.bind("SUPER + SHIFT + 1", hl.dsp.window.move({ workspace = 1 }))
hl.bind("SUPER + SHIFT + 2", hl.dsp.window.move({ workspace = 2 }))
hl.bind("SUPER + SHIFT + 3", hl.dsp.window.move({ workspace = 3 }))
hl.bind("SUPER + SHIFT + 4", hl.dsp.window.move({ workspace = 4 }))
hl.bind("SUPER + SHIFT + 5", hl.dsp.window.move({ workspace = 5 }))
hl.bind("SUPER + SHIFT + 6", hl.dsp.window.move({ workspace = 6 }))
hl.bind("SUPER + SHIFT + 7", hl.dsp.window.move({ workspace = 7 }))
hl.bind("SUPER + SHIFT + 8", hl.dsp.window.move({ workspace = 8 }))
hl.bind("SUPER + SHIFT + 9", hl.dsp.window.move({ workspace = 9 }))
hl.bind("SUPER + SHIFT + 0", hl.dsp.window.move({ workspace = 10 }))
hl.bind("SUPER + BRACKETRIGHT", hl.dsp.window.move({ workspace = 11 }))
hl.bind("SUPER + SHIFT + U", hl.dsp.window.move({ workspace = "e+1" }))
hl.bind("SUPER + SHIFT + I", hl.dsp.window.move({ workspace = "e-1" }))

-- Focus Navigation
hl.bind("SUPER + H", hl.dsp.focus({ direction = "left" }))
hl.bind("SUPER + J", hl.dsp.focus({ direction = "down" }))
hl.bind("SUPER + K", hl.dsp.focus({ direction = "up" }))
hl.bind("SUPER + L", hl.dsp.focus({ direction = "right" }))

-- Window Movement
hl.bind("SUPER + SHIFT + H", hl.dsp.window.move({ direction = "l" }))
hl.bind("SUPER + SHIFT + J", hl.dsp.window.move({ direction = "d" }))
hl.bind("SUPER + SHIFT + K", hl.dsp.window.move({ direction = "u" }))
hl.bind("SUPER + SHIFT + L", hl.dsp.window.move({ direction = "r" }))

-- Special Controls 
hl.bind("SUPER + TAB", hl.dsp.exec_cmd("dms ipc call lock lock"))
hl.bind("CTRL + SHIFT + XF86AudioMute", hl.dsp.exec_cmd("[float;size 900 700;center] pavucontrol"))
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("dms ipc call audio increment 1"), { locked = true, repeating = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("dms ipc call audio decrement 1"), { locked = true, repeating = true })
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("dms ipc call audio mute"), { locked = true })
hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("dms ipc call audio micmute"), { locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("dms ipc call mpris playPause"), { locked = true })
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("dms ipc call mpris playPause"), { locked = true })
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("dms ipc call mpris previous"), { locked = true })
hl.bind("XF86AudioNext", hl.dsp.exec_cmd("dms ipc call mpris next"), { locked = true })
hl.bind("CTRL + XF86AudioRaiseVolume", hl.dsp.exec_cmd("dms ipc call mpris increment 3"), { locked = true, repeating = true })
hl.bind("CTRL + XF86AudioLowerVolume", hl.dsp.exec_cmd("dms ipc call mpris decrement 3"), { locked = true, repeating = true })

hl.bind("CTRL + SHIFT + F5", hl.dsp.exec_cmd("[float;size 900 700;center] pavucontrol"))
hl.bind("CTRL + F7", hl.dsp.exec_cmd("dms ipc call audio increment 1"), { locked = true, repeating = true })
hl.bind("CTRL + F6", hl.dsp.exec_cmd("dms ipc call audio decrement 1"), { locked = true, repeating = true })
hl.bind("CTRL + F5", hl.dsp.exec_cmd("dms ipc call audio mute"), { locked = true })
hl.bind("CTRL + F8", hl.dsp.exec_cmd("dms ipc call audio micmute"), { locked = true })
hl.bind("CTRL + F10", hl.dsp.exec_cmd("dms ipc call mpris previous"), { locked = true })
hl.bind("CTRL + F11", hl.dsp.exec_cmd("dms ipc call mpris playPause"), { locked = true })
hl.bind("CTRL + F12", hl.dsp.exec_cmd("dms ipc call mpris next"), { locked = true })

hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("dms ipc call brightness increment 5 \"\""), { locked = true, repeating = true })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("dms ipc call brightness decrement 5 \"\""), { locked = true, repeating = true })
hl.bind("CTRL + F4", hl.dsp.exec_cmd("dms ipc call brightness increment 5 \"\""), { locked = true, repeating = true })
hl.bind("CTRL + f3", hl.dsp.exec_cmd("dms ipc call brightness decrement 5 \"\""), { locked = true, repeating = true })

-- Mouse Wheel Navigation
hl.bind("SUPER + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind("SUPER + mouse_up", hl.dsp.focus({ workspace = "e-1" }))
hl.bind("SUPER + CTRL + mouse_down", hl.dsp.window.move({ workspace = "e+1" }))
hl.bind("SUPER + CTRL + mouse_up", hl.dsp.window.move({ workspace = "e-1" }))

-- Move/resize windows with mainMod + LMB/RMB and dragging
hl.bind("SUPER + mouse:272", hl.dsp.window.drag(), { description = "Move window" })
hl.bind("SUPER + mouse:273", hl.dsp.window.resize(), { description = "Resize window" })

-- Move/resize windows with mainMod + LMB/RMB and dragging
hl.bind("SUPER + code:20", hl.dsp.window.resize({ x = -100, y = 0, relative = true }), { description = "Expand window left" })
hl.bind("SUPER + code:21", hl.dsp.window.resize({ x = 100, y = 0, relative = true }), { description = "Shrink window left" })

-- Screenshots
hl.bind("Print", hl.dsp.exec_cmd("dms screenshot"))
hl.bind("CTRL + Print", hl.dsp.exec_cmd("dms screenshot full"))
hl.bind("ALT + Print", hl.dsp.exec_cmd("dms screenshot window"))

