
exec-once = dbus-update-activation-environment --systemd --all
exec-once = systemctl --user start hyprland-session.target
exec-once = systemctl --user start dms
exec-once = systemctl --user start hyprpolkitagent
exec-once = systemctl --user start hypridle
exec-once = ~/.config/hypr/script/battery_monitor.sh
exec-once = kdeconnectd
exec-once = emacs --daemon
exec = notify-send -t 300 -a "System" "hyprland" "config reloaded" 
